[build]
cmd = "pip install -r requirements.txt"

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app"

[variables]
# Variabel environment untuk optimasi
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[phases.build]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[providers]
python = "3.10"
